#!/bin/bash

export DB_HOST=amigodb
export DB_PORT=5432
export DB_USER=amigo
export DB_PASS=password
export DB_NAME=amigo_platform

export POSTGRES_USER=amigo
export POSTGRES_PASSWORD=password
export POSTGRES_DB=amigo_platform

export DOCKER_HOST="tcp://docker:2375" # gitlab needs this to support docker testcontainers
export DOCKER_DRIVER=overlay2          # gitlab needs this to support docker testcontainers
export DOCKER_TLS_CERTDIR=""           # "/certs" gitlab needs this to support docker testcontainers

export GRADLE_USER_HOME=$(pwd)/.gradle

# ensure that there exists a gradle configuration
if [ ! -e build.gradle ]; then exit 1; fi

./gradlew :platform-domain:test :platform-rest:test

mkdir platform-rest/build/test-results/test/platform-domain
cp platform-domain/build/test-results/test/TEST-*.xml platform-rest/build/test-results/test/platform-domain/
./gradlew :platform-rest:asciidoctor :platform-rest:bootJar jacocoTestReport coverageReport


ls -lisa platform-rest/build/
