
variables:
  DOCKER_HOST: "tcp://docker:2375"  # gitlab needs this to support docker testcontainers
  DOCKER_DRIVER: overlay2           # gitlab needs this to support docker testcontainers
  DOCKER_TLS_CERTDIR: ""            # "/certs" gitlab needs this to support docker testcontainers

build & test:
  allow_failure: false
  stage: build
  image: java:8
  services:
    - docker:19.03.0-dind
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - .gradle/wrapper
      - .gradle/caches
  script: ci-bin/ci-build-test
  artifacts:
    paths:
      - platform-rest/build/
    reports:
      junit: platform-rest/build/test-results/test/**/TEST-*.xml


push docker:
  stage: deploy
  allow_failure: true
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - .gradle/wrapper
      - .gradle/caches
  script: |
    docker build --tag "$BACKEND_IMAGE_PATH" -f Dockerfile backend
    docker push "$BACKEND_IMAGE_PATH"

pages:
  stage: deploy
  cache:
    key: pages-public-cache
    paths:
      - public/
  script: ci-bin/ci-docs-pages
  artifacts:
    paths:
      - public

