# original source: https://github.com/sameersbn/docker-gitlab/blob/master/docker-compose.yml
version: '3.5'

# please research https://docs.docker.com/compose/environment-variables/ for howto setup your environment
services:

  postgres:
    container_name: postgres
    restart: always
    image: postgres:11.7
    ports: [ "5432:5432" ]
    volumes:
      - amigo-db:/var/lib/postgresql:Z
    env_file: system.env
    environment:
      - DB_EXTENSION=pg_trgm

volumes:
  sock:
  amigo-db:


