= OSSI Austria - amigo-platform API Rest Docs
Florian Hintermeier;
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:
:operation-curl-request-title: Example request
:operation-http-response-title: Example response

[[overview]]
= Overview

[[overview-http-verbs]]
== HTTP verbs

RESTful notes tries to adhere as closely as possible to standard HTTP and REST conventions in its
use of HTTP verbs.

|===
| Verb | Usage

| `GET`
| Used to retrieve a resource. Will return 200.

| `POST`
| Used to create a new resource. Will return 201 for success.

| `PUT`
| Used to update an existing resource as an idempotent call. May also create the resource in
rare cases, e.g. if it a singleton resource. Will return 200 with Content, 204 without Content

| `PATCH`
| Used to update an existing resource, including partial updates. Will return 200 with Content, 204 without Content

| `DELETE`
| Used to delete an existing resource. Will return 204
|===

[[overview-http-status-codes]]
== HTTP status codes

RESTful notes tries to adhere as closely as possible to standard HTTP and REST conventions in its
use of HTTP status codes.

|===
| Status code | Usage

| `200 OK`
|  * The request completed successfully
* An update to an existing resource has been applied successfully

| `201 Created`
| A new resource has been created successfully. The resource's URI is available from the response's
`Location` header

| `204 No Content`
| An update to an existing resource has been applied successfully

| `400 Bad Request`
| The request was malformed. The response body will include an error providing further information.

| `401 Unauthorized`
| User is not logged in and Authorization is necessary

| `403 Forbidden`
| User is authenticated but Authorization is not given on this resource

| `404 Not Found`
| The requested resource did not exist, the URL describes nothing

| `405 Method not allowed`
| The requested path does not support this operation

| `409 Conflict`
| Another similar resource already exist, Creation is not possible

| `415 Unsupported Media Type`
| Only json is supported

| `451 Unavailable for legal reasons`
| A create or update request cannot be accepted due to use of reserved/restricted input

|===

[[overview-headers]]
== Headers

=== Requests

Every authenticated request needs following header(s):

[source]
----
Content-Type: application/json
Accept: application/json
PRIVATE-TOKEN: $SECRET_PRIVATE_TOKEN
----

The Private Token can be obtained during authentication

=== Response

[source]
----
Content-Type: application/json;charset=UTF-8
Content-Length: $NUMBER
----

[[overview-errors]]
== Errors

Whenever an error response (status code >= 400) is returned, the body will contain a JSON object
that describes the problem. The error object has the following structure:

include::{snippets}/register-fail/response-fields.adoc[]

For example, a request that attempts to register a user with a existing username
`400 Bad Request` response:

include::{snippets}/register-fail/http-response.adoc[]

[[authentication]]
== Authentication - /auth

[[authentication-register]]
=== POST /auth/register


operation::register-success[snippets='curl-request,request-fields,http-response,response-fields']

[[authentication-login]]
=== POST /auth/login

Login can be executed with the username or the email.

operation::login-success[snippets='curl-request,request-fields,http-response,response-fields']

[[update-profile]]
=== PUT /auth/user

Update own user's information

operation::update-own-profile-success[snippets='curl-request,request-fields,http-response,response-fields']

=== PUT /auth/update/:user_id

Update user's information, can be used by Admins or by that user itself.

operation::update-profile-success[snippets='curl-request,request-fields,http-response,response-fields']

=== GET /auth/whoami

Get user short profile info

operation::who-am-i[snippets='curl-request,http-response,response-fields']

=== GET /auth/check/token

Check token is correct and alive

operation::check-token[snippets='curl-request,http-response,response-fields']

[[password-management]]
= Passwords management - /password
== Password reset request - POST /password/reset

operation::password-reset-successful[snippets='curl-request,request-parameters,response-body']

== Password reset confirmation - POST /password/reset/confirm

operation::password-reset-confirmation[snippets='curl-request,request-body,response-body']

[[resources]]
= Resources

[[projects]]
== Projects - /projects, /code-projects, /data-projects

Projects are abstract entities with the subtypes DataProject and CodeProject.
For many requests, Projects can be used, but create or update operations, you must use the specific /data-project and /code-project endpoints

=== GET /projects

All *accessible* Projects (own, shared, public)

operation::project-retrieve-accessible[snippets='curl-request,response-body,response-fields']

=== GET /projects/own

All *own* Projects (created by user)

operation::project-retrieve-own[snippets='curl-request']

=== GET /projects/my

All *own* (created by user) and *shared* (user or group is member of ) Projects

operation::project-retrieve-my[snippets='curl-request']

=== GET /projects/starred

All *accessible* Projects *(own,shared,public)* which the user starred.

operation::project-retrieve-starred[snippets='curl-request']

=== GET /projects/public/all

Public projects (can include own and shared), but without paging.

operation::project-retrieve-public-all[snippets='curl-request']

=== GET /projects/:id

operation::data-project-retrieve-one[snippets='curl-request,response-body,response-fields']

=== GET /projects/slug/:slug

operation::projects-retrieve-by-slug[snippets='curl-request,response-body,response-fields']

=== GET /projects/namespace/:namespace

operation::projects-retrieve-by-namespace[snippets='curl-request,response-body,response-fields']

=== GET /projects/:namespace/:slug

operation::data-project-retrieve-one-by-namespace-slug[snippets='curl-request,response-body,response-fields']

=== GET /projects/:namespace/:slug/processor

operation::data-processors-codeproject-retrieve-one-by-namespace-slug[snippets='curl-request,response-body,response-fields']
