= OSSI Austria - amigo-platform API Rest Docs
Florian Hintermeier;
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:
:operation-curl-request-title: Example request
:operation-http-response-title: Example response

[[overview]]
= Overview

*amigo-platform* is the main backend application for the amigo project.
It will provide features and mechanisms for the following problems:

* Authentication (login and token management)
* Authorisation (permissions and groups)
* User Management (Accounts, Persons, Groups)
* Notification and messaging services
* Multimedia management via MinIO integration
* Video/audio call management via Jitsi integration

[[overview-http-verbs]]
== HTTP verbs

RESTful notes tries to adhere as closely as possible to standard HTTP and REST conventions in its use of HTTP verbs.

|===
| Verb | Usage

| `GET`
| Used to retrieve a resource.
Will return 200.

| `POST`
| Used to create a new resource.
Will return 201 for success.

| `PUT`
| Used to update an existing resource as an idempotent call.
May also create the resource in rare cases, e.g. if it a singleton resource.Will return 200 with Content, 204 without Content

| `PATCH`
| Used to update an existing resource, including partial updates.
Will return 200 with Content, 204 without Content

| `DELETE`
| Used to delete an existing resource.
Will return 204
|===

[[overview-http-status-codes]]
== HTTP status codes

RESTful notes tries to adhere as closely as possible to standard HTTP and REST conventions in its use of HTTP status codes.

|===
| Status code | Usage

| `200 OK`
|  The request completed successfully.
An update to an existing resource has been applied successfully

| `201 Created`
| A new resource has been created successfully.
The resource's URI is available from the response's
`Location` header

| `204 No Content`
| An update to an existing resource has been applied successfully

| `400 Bad Request`
| The request was malformed.
The response body will include an error providing further information.

| `401 Unauthorized`
| User is not logged in and Authorization is necessary

| `403 Forbidden`
| User is authenticated but Authorization is not given on this resource

| `404 Not Found`
| The requested resource did not exist, the URL describes nothing

| `405 Method not allowed`
| The requested path does not support this operation

| `409 Conflict`
| Another similar resource already exist, Creation is not possible

| `415 Unsupported Media Type`
| Only json is supported

| `451 Unavailable for legal reasons`
| A create or update request cannot be accepted due to use of reserved/restricted input

|===

[[overview-headers]]
== Headers

=== Requests

Every authenticated request needs at least the following header(s):

[source]
----
Content-Type: application/json
Accept: application/json
Authorization: Bearer $SECRET_ACCESS_TOKEN
Amigo-Person-Id: $UUID of own person
----

*Attention*: Currently providing the *Amigo-Person-Id* information is optional, as the first Person of Account will be used otherwise.
As amigo-platform is designed to be a multi-group user system, an Account can have several Persons in different Groups.
Therefore, the usage of *Amigo-Person-Id* is meant as specific authentication and encouraged.

Additionally it is useful to provide the

The Private Token can be obtained during authentication

=== Response

[source]
----
Content-Type: application/json;charset=UTF-8
Content-Length: $NUMBER
----

[[overview-errors]]
== Errors

Whenever an error response (status code >= 400) is returned, the body will contain a JSON object that describes the problem.
The error object has the following structure:

operation::register-fail[snippets='response-fields']

For example, a request that attempts to register a user with an existing username
`400 Bad Request` response:

operation::register-fail[snippets='http-response']

= User & Groups

[[authentication]]
== Authentication - /auth

[[authentication-register]]
=== POST /auth/register

operation::register-success[snippets='curl-request,request-fields,http-response,response-fields']

Or use explicit Group registering:

operation::register-explicit-success[snippets='curl-request,request-fields,http-response']

[[authentication-register-analogue]]
=== POST /auth/register-analogue

operation::register-analogue-success[snippets='curl-request,request-fields,http-response,response-fields']

[[authentication-login]]
=== POST /auth/login

operation::login-success[snippets='curl-request,request-fields,http-response,response-fields']

=== POST /auth/refresh-token

When performing this action to "refresh a token" you get a new "access token".

operation::refresh-token-success[snippets='curl-request,request-fields,http-response,response-fields']

=== GET /auth/account

Get user short profile info, when already logged in.

operation::account[snippets='curl-request,http-response,response-fields']

[[account-set-fcm-token]]
=== POST /auth/fcm-token

Set the new Firebase Cloud Messaging (FCM) token for the current user.
No Data as response.

operation::account-set-fcm-token[snippets='curl-request,request-fields,http-response']

[[groups]]
== Groups - /groups

Groups contain all necessary Person profiles inside them.
A User can just access the Groups where they have a Person profile and is at least MEMBER (default).

A Group can contain at max 1 ANALOGUE Person.

=== Group Model

operation::groups-my-success[snippets='http-response,response-fields']

[[groups-create]]
=== POST /groups/

Creator is automatically the OWNER of the new Group.
Owner cannot be removed or lose privileges

operation::groups-create[snippets='curl-request,request-fields,http-response']

[[groups-change]]
=== PATCH /groups/:id

*Name* of Group can be changed

operation::groups-change[snippets='curl-request,request-fields,http-response']

[[groups-member-add]]
=== POST /groups/:id/members

*Email* is used to find an existing Account and create a new Person in this Group.
*Name* and *MembershipType* must be initialised

operation::groups-member-add[snippets='curl-request,request-fields,http-response']

[[groups-member-change]]
=== PATCH /groups/:id/members/:personId

Change privilege of a member.

*Attention:* OWNERS cannot be decreased in privilege.

operation::groups-member-change[snippets='curl-request,request-fields,http-response']

[[groups-member-remove]]
=== DELETE /groups/:id/members/:personId

Delete a non-OWNER of a Group.
Note: This endpoint might change to not return a result

operation::groups-member-remove[snippets='curl-request,http-response']

[[groups-my]]
=== GET /groups/

Fetch all Groups of own User.

operation::groups-my-success[snippets='curl-request,http-response']

[[groups-one]]
=== GET /groups/:id

Fetch one Group which own User can access.
Endpoint will return 404 for Groups which cannot be found or accessed.

operation::groups-one-success[snippets='curl-request,http-response']

[[groups-filtered]]
=== GET /groups/filtered?personId=<UUID>&name=<String>

Filter accessible Groups for *own* Person and/or Group name

operation::groups-filtered-success[snippets='curl-request,request-parameters,http-response']

[[persons]]
== Persons - /persons

=== GET /persons/:id/avatar.*

Hint: Use Person.avatarUrl to get the suffix.

it will react in three different ways:

* respond with the Image as content, watch out for content-type and length
* redirect to another URL, which should be an image
* respond with a 404 when no usable avatar is found

operation::persons-avatar-success[snippets='curl-request']

=== GET /persons/:id/public/:key

Public endpoint for Avatars.
No need for authentication, but a key has to be provided.
As $key, the value of "avatarUrl" has to be used.

Hint: Use Person.avatarUrl to get the key.

it will react in three different ways:

* respond with the Image as content, watch out for content-type and length
* redirect to another URL, which should be an image
* respond with a 404 when no usable avatar is found

operation::persons-avatar-public-success[snippets='curl-request']

=== Example for Redirect of external URL:

operation::persons-avatar-success[snippets='http-response']

[[profile]]
== Profile - /profile

[[profile-get]]
=== GET /profile

Fetch Profile of own user

operation::profile-success[snippets='curl-request,http-response,response-fields']

[[profile-patch]]
=== PATCH /profile

Update Profile of own user: Name and avatarUrl can be changed

operation::profile-change-success[snippets='curl-request,request-fields,http-response']

[[profile-post]]
=== POST /profile

Update Avatar with a new file

operation::profile-upload-avatar-success[snippets='curl-request,http-response']

= Multimedia Management

[[albums]]
== Albums

=== GET /albums/own - All my Albums

operation::albums-own[snippets='curl-request,http-response,response-fields']

=== Create new Album - POST /albums

operation::albums-create[snippets='curl-request,request-fields,http-response']

=== GET /albums/shared - All Albums shared with me

operation::albums-shared[snippets='curl-request,http-response']

=== GET /albums/:id

operation::albums-one[snippets='curl-request,http-response']

== Multimedias

=== GET /multimedias/own - All my Multimedia

operation::multimedias-own[snippets='curl-request,http-response,response-fields']

=== Create & upload new Multimedia - POST /multimedias

File Content must be provided as a MultiPart file in the "form-data" body.
ReceiverId and SenderId can be provided as URL request param or also as fields.

operation::multimedias-create[snippets='curl-request,request-parameters,http-response']

=== GET /multimedias/:id

operation::multimedias-one[snippets='curl-request,http-response']

=== GET /multimedias/:id/file

operation::multimedias-get-file[snippets='curl-request,http-response']

=== POST /multimedias/:id/file

operation::multimedias-update-file[snippets='curl-request,http-response']

= NFC Tags & Information

== General Structure

operation::nfcs-create[snippets='response-fields']

== Create new NFC - POST /nfc

You can optionally set linked Album OR linked Person.
If both are provided, Album will be linked.

operation::nfcs-create[snippets='curl-request,request-fields,http-response,response-fields']

== Change NFC - PATCH /nfc/:id

You can set Name and ONE OF linked Album OR linked Person.
If both are provided, Album will be linked.

operation::nfcs-change[snippets='curl-request,request-fields,http-response,response-fields']

== Get all own NFC - GET /nfc/own

operation::nfcs-own[snippets='curl-request,http-response']

== Get all created NFC - GET /nfc/created

operation::nfcs-created[snippets='curl-request,http-response']

== Get one NFC - GET /nfc/:id

operation::nfcs-one[snippets='curl-request,http-response']

== Delete one NFC - DELETE /nfc/:id

operation::nfcs-delete[snippets='curl-request,http-response']

= Sendables

All Sendables behave similar and share a big amount of code.
See the first example of Sendable endpoints used on Message for further information.

As a multi-user platform, amigo-platform needs to know which Person is meant to be the owner of the request.

Every idempotent sendable request takes an optional "personId" parameter:

|===
|Parameter|Description

|`+personId?+`
|UUID of own Person to this request

|===

[[messages]]
== Messages

=== Create new Message - POST /messages

operation::messages-create[snippets='curl-request,request-parameters,http-response,response-fields']

=== Filter Messages - GET /messages/filter?receiverId=<UUID>&senderId=<UUID>

operation::messages-filter[snippets='curl-request,http-response']

=== GET /messages/received - All my retrieved

operation::messages-received[snippets='curl-request,http-response']

=== GET /messages/sent - All my sent

operation::messages-sent[snippets='curl-request,http-response']

=== GET /messages/:id

operation::messages-one[snippets='curl-request,http-response']

=== PATCH /messages/:id/set-retrieved - Set Message as "retrieved"

operation::messages-set-retrieved[snippets='curl-request,http-response']

[[calls]]
== Calls

=== Create & start new Jitsi calls - POST /calls

File Content must be provided as a MultiPart file in the "form-data" body.
ReceiverId and SenderId can be provided as URL request param or also as fields.

*Note*: The kind-of-secret JWT Jitsi token is only set by create, get-one, and accept.

operation::calls-create[snippets='curl-request,request-parameters,http-response,response-fields']

=== Filter calls - GET /calls/filter?receiverId=<UUID>&senderId=<UUID>

operation::calls-filter[snippets='curl-request,http-response']

=== GET /calls/received - All my retrieved Calls

operation::calls-received[snippets='curl-request,http-response']

=== GET /calls/sent - All my started Calls

operation::calls-sent[snippets='curl-request,http-response']

=== GET /calls/:id

*Note*: The kind-of-secret JWT Jitsi token is only set by create, get-one, and accept.

operation::calls-one[snippets='curl-request,http-response']

=== PATCH /calls/:id/accept - Accept a call

Can be called by callee to accept an incoming call.
*Note*: The kind-of-secret JWT Jitsi token is only set by create, get-one, and accept.

operation::calls-accept[snippets='curl-request,http-response']

=== PATCH /calls/:id/cancel - Cancel an outgoing own call

Can be called by caller to cancel an outgoing own call.

operation::calls-cancel[snippets='curl-request,http-response']

=== PATCH /calls/:id/deny - Denies an incoming call

Can be called by callee to deny an incoming call.

operation::calls-deny[snippets='curl-request,http-response']

=== PATCH /calls/:id/finish - Finishes an incoming/outgoing call

Can be called by both parties to finish a running call.

operation::calls-finish[snippets='curl-request,http-response']

