= OSSI Austria - amigo-platform API Rest Docs
Florian Hintermeier;
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:
:operation-curl-request-title: Example request
:operation-http-response-title: Example response

[[overview]]
= Overview

*amigo-platform* is the main backend application for the amigo project.
It will provide features and mechanisms for the following problems:

* Authentication (login and token management)
* Authorisation (permissions and groups)
* User Management (Accounts, Persons, Groups)
* Notification and messaging services
* Multimedia management via MinIO integration
* Video/audio call management via Jitsi integration

[[overview-http-verbs]]
== HTTP verbs

RESTful notes tries to adhere as closely as possible to standard HTTP and REST conventions in its use of HTTP verbs.

|===
| Verb | Usage

| `GET`
| Used to retrieve a resource.
Will return 200.

| `POST`
| Used to create a new resource.
Will return 201 for success.

| `PUT`
| Used to update an existing resource as an idempotent call.
May also create the resource in rare cases, e.g. if it a singleton resource.Will return 200 with Content, 204 without Content

| `PATCH`
| Used to update an existing resource, including partial updates.
Will return 200 with Content, 204 without Content

| `DELETE`
| Used to delete an existing resource.
Will return 204
|===

[[overview-http-status-codes]]
== HTTP status codes

RESTful notes tries to adhere as closely as possible to standard HTTP and REST conventions in its use of HTTP status codes.

|===
| Status code | Usage

| `200 OK`
|  The request completed successfully.
An update to an existing resource has been applied successfully

| `201 Created`
| A new resource has been created successfully.
The resource's URI is available from the response's
`Location` header

| `204 No Content`
| An update to an existing resource has been applied successfully

| `400 Bad Request`
| The request was malformed.
The response body will include an error providing further information.

| `401 Unauthorized`
| User is not logged in and Authorization is necessary

| `403 Forbidden`
| User is authenticated but Authorization is not given on this resource

| `404 Not Found`
| The requested resource did not exist, the URL describes nothing

| `405 Method not allowed`
| The requested path does not support this operation

| `409 Conflict`
| Another similar resource already exist, Creation is not possible

| `415 Unsupported Media Type`
| Only json is supported

| `451 Unavailable for legal reasons`
| A create or update request cannot be accepted due to use of reserved/restricted input

|===

[[overview-headers]]
== Headers

=== Requests

Every authenticated request needs following header(s):

[source]
----
Content-Type: application/json
Accept: application/json
Authorization: Bearer $SECRET_ACCESS_TOKEN
----

The Private Token can be obtained during authentication

=== Response

[source]
----
Content-Type: application/json;charset=UTF-8
Content-Length: $NUMBER
----

[[overview-errors]]
== Errors

Whenever an error response (status code >= 400) is returned, the body will contain a JSON object that describes the problem.
The error object has the following structure:

operation::register-fail[snippets='response-fields']

For example, a request that attempts to register a user with an existing username
`400 Bad Request` response:

operation::register-fail[snippets='http-response']

[[authentication]]
== Authentication - /auth

[[authentication-register]]
=== POST /auth/register

operation::register-success[snippets='curl-request,request-fields,http-response,response-fields']

[[authentication-login]]
=== POST /auth/login

Login can be executed with the username or the email.

operation::login-success[snippets='curl-request,request-fields,http-response,response-fields']

[[update-profile]]
=== PUT /auth/register

operation::register-success[snippets='curl-request,request-fields,http-response,response-fields']

=== GET /auth/refresh-token

operation::refresh-token-success[snippets='curl-request,request-fields,http-response,response-fields']

=== GET /auth/whoami

Get user short profile info

operation::who-am-i[snippets='curl-request,http-response,response-fields']

= Common Resources

[[account]]
== Account - /account

Account endpoint is a singular endpoint just for the current user.

[[account-set-fcm-token]]
=== POST /account/set-fcm-token

Set the new Firebase Cloud Messaging (FCM) token for the current user.

operation::account-set-fcm-token[snippets='curl-request,http-response']

[[groups]]
== Groups - /groups

Groups contain all necessary Person profiles inside them.
A User can just access the Groups where they have a Person profile and is at least MEMBER (default).

A Group can contain at max 1 ANALOGUE Person.

[[groups-my]]
=== GET /groups/my

Fetch all Groups of own User.

operation::groups-my-success[snippets='curl-request,http-response,response-fields']

=== GET /groups/:id

Fetch one Group which own User can access.
Endpoint will return 404 for Groups which cannot be found or accessed.

operation::groups-one-success[snippets='curl-request,http-response,response-fields']

=== GET /groups/filtered?personId=<UUID>&name=<String>

Filter accessible Groups for *own* Person and/or Group name

operation::groups-filtered-success[snippets='curl-request,request-parameters,http-response,response-fields']

[[multimedias]]
== Multimedias

=== Create & upload new Multimedia - POST /multimedias

File Content must be provided as a MultiPart file in the "form-data" body.
ReceiverId and SenderId can be provided as URL request param or also as fields.

operation::multimedias-create[snippets='curl-request,http-response,response-fields']

=== GET /multimedias/own - All my Multimedia

operation::multimedias-own[snippets='curl-request,http-response,response-fields']

=== GET /multimedias/:id

operation::multimedias-one[snippets='curl-request,http-response,response-fields']

=== GET /multimedias/:id/file

operation::multimedias-get-file[snippets='curl-request,http-response']

=== POST /multimedias/:id/file

operation::multimedias-update-file[snippets='curl-request,http-response,response-fields']

= Sendables

All Sendables behave similar and share a big amount of code.
See the first example of Sendable endpoints used on Message for further informatio.

[[messages]]
== Messages

=== Create new Message - POST /messages

operation::messages-create[snippets='curl-request,http-response,response-fields']

=== Filter Messages - GET /messages/filter?receiverId=<UUID>&senderId=<UUID>

operation::messages-filter[snippets='curl-request,http-response,response-fields']

=== GET /messages/received - All my retrieved

operation::messages-received[snippets='curl-request,http-response,response-fields']

=== GET /messages/sent - All my sent

operation::messages-sent[snippets='curl-request,http-response,response-fields']

=== GET /messages/:id

operation::messages-one[snippets='curl-request,http-response,response-fields']

=== PATCH /messages/:id/set-retrieved - Set Message as "retrieved"

operation::messages-set-retrieved[snippets='curl-request,http-response,response-fields']


[[calls]]
== Calls

=== Create & start new Jitsi calls - POST /calls

File Content must be provided as a MultiPart file in the "form-data" body.
ReceiverId and SenderId can be provided as URL request param or also as fields.

*Note*: The kind-of-secret JWT Jitsi token is only set by create, get-one, and accept.

operation::calls-create[snippets='curl-request,http-response,response-fields']

=== Filter calls - GET /calls/filter?receiverId=<UUID>&senderId=<UUID>

operation::calls-filter[snippets='curl-request,http-response,response-fields']

=== GET /calls/received - All my retrieved Calls

operation::calls-received[snippets='curl-request,http-response,response-fields']

=== GET /calls/sent - All my started Calls

operation::calls-sent[snippets='curl-request,http-response,response-fields']

=== GET /calls/:id

*Note*: The kind-of-secret JWT Jitsi token is only set by create, get-one, and accept.

operation::calls-one[snippets='curl-request,http-response,response-fields']

=== PATCH /calls/:id/accept - Accept a call

Can be called by callee to accept an incoming call.
*Note*: The kind-of-secret JWT Jitsi token is only set by create, get-one, and accept.

operation::calls-accept[snippets='curl-request,http-response,response-fields']

=== PATCH /calls/:id/cancel - Cancel an outgoing own call

Can be called by caller to cancel an outgoing own call.

operation::calls-cancel[snippets='curl-request,http-response,response-fields']

=== PATCH /calls/:id/deny - Denies an incoming call

Can be called by callee to deny an incoming call.

operation::calls-deny[snippets='curl-request,http-response,response-fields']

=== PATCH /calls/:id/finish - Finishes an incoming/outgoing call

Can be called by both parties to finish a running call.

operation::calls-finish[snippets='curl-request,http-response,response-fields']

