amigo-platform:
  security:
    accessTokenSecret: ${AMIGO_ACCESS_TOKEN_SECRET:asdf1234}
    refreshTokenSecret: ${AMIGO_REFRESH_TOKEN_SECRET:asdf1234asdf}
    accessTokenExpirationSec: 36000
    refreshTokenExpirationSec: 3600000

spring:
  devtools:
    add-properties: false
  data:
    repositories.type: none
    redis:
      repositories:
        enabled: false
  cache.type: simple
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:amigo_platform}
    username: ${DB_USER:amigo}
    password: ${DB_PASSWORD:password}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    generate-ddl: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp.use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: none
  flyway:
    baseline-on-migrate: true


logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %highlight(%-5level) %boldGreen([%thread]) %cyan(%logger{15}.%M [%line]) - %msg%n%throwable'


