spring:
  devtools:
    add-properties: true
  data:
    repositories.type: none
    redis:
      repositories:
        enabled: false
  jpa:
    show-sql: false # true for debugging
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  flyway:
    enabled: false # USE for dev only
